platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang


inputs:
  - name: repo
outputs:
  - name: binary

run:
  dir: repo
  path: go
  args:
  - build
  - -o
  - ../binary/imakarahajimeru
