#resource_types:
#- name: cappyzawa-cf
#  type: registry-image
#  source:
#    repository: cappyzawa/cf-resource
#    tag: 6.28.0

resources:
- name: repo
  type: git
  icon: github-circle
  #webhook_token: ((webhook-token))
  source:
    uri: https://github.com/bookun/imakarahajimeru
    username: bookun
    password: ((password))
    branch: master


- name: gh-pre-release
  type: github-release
  icon: package-variant-closed
  source:
    owner: bookun
    repository: imakarahajimeru
    access_token: ((github-access-token))
    release: false
    pre_release: true
    tag_filter: v*.*.*

- name: gh-release
  type: github-release
  icon: package-variant-closed
  source:
    owner: bookun
    repository: imakarahajimeru
    access_token: ((github-access-token))
    pre_release: true
    tag_filter: v*.*.*

- name: cf
  type: cappyzawa-cf
  icon: cloud
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: true

- name: cf-canary
  type: cappyzawa-cf
  icon: cloud
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: true


- name: version
  type: semver
  icon: tag
  source:
    uri: https://github.com/bookun/imakarahajimeru
    driver: git
    branch: master
    file: version
    username: bookun
    password: ((password))
    commit_message: "[ci skip] bump to %version%"

    #- name: s3
    #  type: s3
    #  source:
    #    bucket: ((s3-bucket))
    #    access_key_id: ((s3-access))
    #    secret_access_key: ((s3-secret))
    #    region_name: ap-northeast-1


jobs:
  #- name: s3-upload
  #  plan:
  #  - get: repo
  #  - task: build
  #    file: repo/build.yml
  #  - put: s3
  #    params:
  #      file: repo/manifest.yml
  #  - put: s3
  #    params:
  #      file: binary/imakarahajimeru

- name: stgMOCK-deploy
  plan:
  - get: repo
  - put: version
    params:
      bump: minor
  - task: set-domain
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: alpine}}
      inputs:
      - name: repo
      outputs:
      - name: out
      params:
        DOMAIN: ((domain))
      run:
        path: sh
        args:
        - -c
        - |
          sed -e "s/<<FIX_ME>>/${DOMAIN}/g" repo/manifest.yml > out/manifest.yml
          sed -e "s/<<FIX_ME>>/${DOMAIN}/g" repo/manifest-canary.yml > out/manifest-canary.yml
  - task: build
    file: repo/build.yml
  - in_parallel:
    - put: cf
      params:
        manifest: out/manifest.yml
        # overwrite "path" in manifest
        path: binary
    - put: cf-canary
      params:
        manifest: out/manifest-canary.yml
        #overwrite "path" in manifest
        path: binary

  - put: gh-pre-release
    params:
      name: version/version
      tag: version/version
      tag_prefix: v
      globs:
      - binary/imakarahajimeru
      - repo/manifest.yml

- name: proMOCK-deploy
  plan:
  - get: gh-release
    #- put: cf
    #  params:
    #    manifest: out/manifest.yml
    #    # overwrite "path" in manifest
    #    path: binary
  - put: gh-release
    params:
      name: gh-release/version
      tag: gh-release/version
      globs:
      - gh-release/imakarahajimeru
      - gh-release/manifest.yml
