resources:
- name: repo
  type: git
  icon: github-circle
  #webhook_token: ((webhook-token))
  source:
    uri: https://github.com/bookun/imakarahajimeru

- name: gh-release
  type: github-release
  source:
    owner: bookun
    repository: imakarahajimeru

- name: cf
  type: cappyzawa-cf
  icon: cloud
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    space: ((cf-space))
    skip_cert_check: true

jobs:
- name: tag
  plan:
  - get: repo
    trigger: true
  - get: gh-release
    params:
      globs: 
      - imakarahajimeru
        #- put: cf
        #  params:
        #    manifest: 
