resource_types:
  - name: cappyzawa-cf
    type: registry-image
    source:
      repository: cappyzawa/cf-resource
      tag: 6.28.0

resources:
- name: repo
  type: git
  icon: github-circle
  #webhook_token: ((webhook-token))
  source:
    uri: https://github.com/bookun/imakarahajimeru

- name: gh-release
  type: github-release
  source:
    owner: bookun
    repository: imakarahajimeru
    access_token: ((github-access-token))
    tag_filter: v*.*.*

- name: cf
  type: cappyzawa-cf
  icon: cloud
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: ((cf-space))
    skip_cert_check: true

- name: version
  type: semver
  source:
    uri: https://github.com/bookun/imakarahajimeru
    driver: git
    branch: master
    file: version
    username: bookun
    password: ((password))


jobs:
- name: tag
  plan:
  - in_parallel:
    - get: repo
      #trigger: true
    - get: gh-release
      params:
        globs:
        - imakarahajimeru
  - task: set-domain
    config:
      platform: linux
      image_resource: {type: docker-image, source: {repository: alpine}}
      inputs:
      - name: repo
      outputs:
      - name: out
      params:
        DOMAIN: ((domain))
      run:
        path: sh
        args:
        - -c
        - |
          sed -e "s/<<FIX_ME>>/${DOMAIN}/g" repo/manifest.yml > out/manifest.yml
  - put: cf
    params:
      manifest: out/manifest.yml
      # overwrite "path" in manifest
      path: gh-release

- name: version
  plan:
  - in_parallel:
    - get: repo
    - get: version
      params: {bump: minor}
  - task: build
    file: repo/build.yml
  - put: gh-release
    params:
      name: version/version
      tag: version/version
      tag_prefix: v
      globs:
      - binary/imakarahajimeru
  - put: version
